package edu.eci.cosw.persistenceexercises.simplepersistencelayer;
// Generated Feb 15, 2015 4:44:56 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Alimento generated by hbm2java
 */
@Entity
@Table(name="Alimentos")
public class Alimento  implements java.io.Serializable {


     private AlimentoId id;
     private Categoria categorias;
     private Producto productos;
     private String nombre;
     
    public Alimento() {
    }

	
    public Alimento(Categoria categorias, Producto productos, String nombre) {
        this.categorias = categorias;
        this.productos = productos;
        this.nombre = nombre;
    }
    
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="productosIdProductos", column=@Column(name="Productos_idProductos", nullable=false) ), 
        @AttributeOverride(name="productosSucursalesIdSucursales", column=@Column(name="Productos_Sucursales_idSucursales", nullable=false) ) } )
    public AlimentoId getId() {
        return this.id;
    }
    
    public void setId(AlimentoId id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Categorias_idCategorias", nullable=false)
    public Categoria getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categoria categorias) {
        this.categorias = categorias;
    }

    @OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Producto getProductos() {
        return this.productos;
    }
    
    public void setProductos(Producto productos) {
        this.productos = productos;
    }

    
    @Column(name="Nombre", nullable=false, length=70)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
}


