package edu.eci.cosw.persistenceexercises.simplepersistencelayer;
// Generated Feb 15, 2015 4:44:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Combo generated by hbm2java
 */
@Entity
@Table(name="Combos")
public class Combo  implements java.io.Serializable {

     private ComboId id;
     private Producto productos;
     private String nombre;
     private Set<Alimento> alimentoses = new HashSet<Alimento>(0);

    public Combo() {
    }

	
    public Combo(Producto productos) {
        this.productos = productos;
    }
    public Combo(Producto productos, String nombre, Set alimentoses) {
       this.productos = productos;
       this.nombre = nombre;
       this.alimentoses = alimentoses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="productosIdProductos", column=@Column(name="Productos_idProductos", nullable=false) ), 
        @AttributeOverride(name="productosSucursalesIdSucursales", column=@Column(name="Productos_Sucursales_idSucursales", nullable=false) ) } )
    public ComboId getId() {
        return this.id;
    }
    
    public void setId(ComboId id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Producto getProductos() {
        return this.productos;
    }
    
    public void setProductos(Producto productos) {
        this.productos = productos;
    }

    
    @Column(name="Nombre", length=70)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="combos")
    public Set getAlimentoses() {
        return this.alimentoses;
    }
    
    public void setAlimentoses(Set alimentoses) {
        this.alimentoses = alimentoses;
    }




}


