package edu.eci.cosw.persistenceexercises.simplepersistencelayer;
// Generated Feb 15, 2015 4:44:56 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ComboId generated by hbm2java
 */
@Embeddable
public class ComboId  implements java.io.Serializable {


     private int productosIdProductos;
     private int productosSucursalesIdSucursales;

    public ComboId() {
    }

    public ComboId(int productosIdProductos, int productosSucursalesIdSucursales) {
       this.productosIdProductos = productosIdProductos;
       this.productosSucursalesIdSucursales = productosSucursalesIdSucursales;
    }
   


    @Column(name="Productos_idProductos", nullable=false)
    public int getProductosIdProductos() {
        return this.productosIdProductos;
    }
    
    public void setProductosIdProductos(int productosIdProductos) {
        this.productosIdProductos = productosIdProductos;
    }


    @Column(name="Productos_Sucursales_idSucursales", nullable=false)
    public int getProductosSucursalesIdSucursales() {
        return this.productosSucursalesIdSucursales;
    }
    
    public void setProductosSucursalesIdSucursales(int productosSucursalesIdSucursales) {
        this.productosSucursalesIdSucursales = productosSucursalesIdSucursales;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ComboId) ) return false;
		 ComboId castOther = ( ComboId ) other; 
         
		 return (this.getProductosIdProductos()==castOther.getProductosIdProductos())
 && (this.getProductosSucursalesIdSucursales()==castOther.getProductosSucursalesIdSucursales());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProductosIdProductos();
         result = 37 * result + this.getProductosSucursalesIdSucursales();
         return result;
   }   


}


