package edu.eci.cosw.persistenceexercises.simplepersistencelayer;
// Generated Feb 15, 2015 4:44:56 PM by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MetodoDePago generated by hbm2java
 */
@Entity
@Table(name="MetodosDePago")
public class MetodoDePago  implements java.io.Serializable {


     private int idMetodosDePago;
     private String nombre;
     
    public MetodoDePago() {
    }

	
    public MetodoDePago(int idMetodosDePago) {
        this.idMetodosDePago = idMetodosDePago;
    }
    public MetodoDePago(int idMetodosDePago, String nombre) {
       this.idMetodosDePago = idMetodosDePago;
       this.nombre = nombre;
       
    }
   
    @Id
    @Column(name="idMetodosDePago", unique=true, nullable=false)
    public int getIdMetodosDePago() {
        return this.idMetodosDePago;
    }
    
    public void setIdMetodosDePago(int idMetodosDePago) {
        this.idMetodosDePago = idMetodosDePago;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}


