package edu.eci.cosw.persistenceexercises.simplepersistencelayer;
// Generated Feb 15, 2015 4:44:56 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductoId generated by hbm2java
 */
@Embeddable
public class ProductoId  implements java.io.Serializable {


     private int idProductos;
     private int sucursalesIdSucursales;

    public ProductoId() {
    }

    public ProductoId(int idProductos, int sucursalesIdSucursales) {
       this.idProductos = idProductos;
       this.sucursalesIdSucursales = sucursalesIdSucursales;
    }
   


    @Column(name="idProductos", nullable=false)
    public int getIdProductos() {
        return this.idProductos;
    }
    
    public void setIdProductos(int idProductos) {
        this.idProductos = idProductos;
    }


    @Column(name="Sucursales_idSucursales", nullable=false)
    public int getSucursalesIdSucursales() {
        return this.sucursalesIdSucursales;
    }
    
    public void setSucursalesIdSucursales(int sucursalesIdSucursales) {
        this.sucursalesIdSucursales = sucursalesIdSucursales;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductoId) ) return false;
		 ProductoId castOther = ( ProductoId ) other; 
         
		 return (this.getIdProductos()==castOther.getIdProductos())
 && (this.getSucursalesIdSucursales()==castOther.getSucursalesIdSucursales());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdProductos();
         result = 37 * result + this.getSucursalesIdSucursales();
         return result;
   }   


}


