package edu.eci.cosw.persistenceexercises.simplepersistencelayer;
// Generated Feb 15, 2015 4:44:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="Productos")
public class Producto  implements java.io.Serializable {

    private ProductoId id;
    private Sucursal sucursales;
    private float precio;
    private Set<Pedido> pedidoses = new HashSet<Pedido>(0);

    public Producto() {
    }

	
    public Producto(ProductoId id, Sucursal sucursales, float precio) {
        this.id = id;
        this.sucursales = sucursales;
        this.precio = precio;
    }
    public Producto(ProductoId id, Sucursal sucursales, float precio, Set pedidoses) {
       this.id = id;
       this.sucursales = sucursales;
       this.precio = precio;
       this.pedidoses = pedidoses;
    }
   
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="idProductos", column=@Column(name="idProductos", nullable=false) ), 
        @AttributeOverride(name="sucursalesIdSucursales", column=@Column(name="Sucursales_idSucursales", nullable=false) ) } )
    public ProductoId getId() {
        return this.id;
    }
    
    public void setId(ProductoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Sucursales_idSucursales", nullable=false, insertable=false, updatable=false)
    public Sucursal getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursal sucursales) {
        this.sucursales = sucursales;
    }

    
    @Column(name="Precio", nullable=false, precision=12, scale=0)
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="Pedidos_Productos", catalog="coswg1", joinColumns = { 
        @JoinColumn(name="Producto_idProductos", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Pedidos_idPedidos", nullable=false, updatable=false) })
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }




}


