package edu.eci.cosw.persistenceexercises.simplepersistencelayer;
// Generated Feb 15, 2015 4:44:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name="Sucursales")
public class Sucursal  implements java.io.Serializable {


     private Integer idSucursales;
     private Franquicia franquicias;
     private PlazoletaComida plazoletaComidas;
     private Set productoses = new HashSet(0);

    public Sucursal() {
    }

	
    public Sucursal(Franquicia franquicias, PlazoletaComida plazoletaComidas) {
        this.franquicias = franquicias;
        this.plazoletaComidas = plazoletaComidas;
    }
    public Sucursal(Franquicia franquicias, PlazoletaComida plazoletaComidas, Set productoses) {
       this.franquicias = franquicias;
       this.plazoletaComidas = plazoletaComidas;
       this.productoses = productoses;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idSucursales", unique=true, nullable=false)
    public Integer getIdSucursales() {
        return this.idSucursales;
    }
    
    public void setIdSucursales(Integer idSucursales) {
        this.idSucursales = idSucursales;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Franquicias_idFranquicia", nullable=false)
    public Franquicia getFranquicias() {
        return this.franquicias;
    }
    
    public void setFranquicias(Franquicia franquicias) {
        this.franquicias = franquicias;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="PlazoletaComidas_idPlazoletaComidas", referencedColumnName="idPlazoletaComidas", nullable=false), 
        @JoinColumn(name="PlazoletaComidas_ciudad", referencedColumnName="ciudad", nullable=false) } )
    public PlazoletaComida getPlazoletaComidas() {
        return this.plazoletaComidas;
    }
    
    public void setPlazoletaComidas(PlazoletaComida plazoletaComidas) {
        this.plazoletaComidas = plazoletaComidas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sucursales")
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }




}


