package edu.eci.cosw.persistenceexercises.simplepersistencelayer;
// Generated Feb 15, 2015 1:34:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Alimentos generated by hbm2java
 */
@Entity
@Table(name="Alimentos"
    ,catalog="coswg1"
)
public class Alimentos  implements java.io.Serializable {


     private int productoIdProductos;
     private Categorias categorias;
     private Combos combos;
     private Productos productos;
     private String nombre;

    public Alimentos() {
    }

	
    public Alimentos(Categorias categorias, Productos productos, String nombre) {
        this.categorias = categorias;
        this.productos = productos;
        this.nombre = nombre;
    }
    public Alimentos(Categorias categorias, Combos combos, Productos productos, String nombre) {
       this.categorias = categorias;
       this.combos = combos;
       this.productos = productos;
       this.nombre = nombre;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="productos"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="Producto_idProductos", unique=true, nullable=false)
    public int getProductoIdProductos() {
        return this.productoIdProductos;
    }
    
    public void setProductoIdProductos(int productoIdProductos) {
        this.productoIdProductos = productoIdProductos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Categorias_idCategorias", nullable=false)
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Combos_Producto_idProductos")
    public Combos getCombos() {
        return this.combos;
    }
    
    public void setCombos(Combos combos) {
        this.combos = combos;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }

    
    @Column(name="Nombre", nullable=false, length=70)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


