package edu.eci.cosw.persistenceexercises.simplepersistencelayer;
// Generated Feb 15, 2015 1:34:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorias generated by hbm2java
 */
@Entity
@Table(name="Categorias"
    ,catalog="coswg1"
)
public class Categorias  implements java.io.Serializable {


     private String idCategorias;
     private Set alimentoses = new HashSet(0);

    public Categorias() {
    }

	
    public Categorias(String idCategorias) {
        this.idCategorias = idCategorias;
    }
    public Categorias(String idCategorias, Set alimentoses) {
       this.idCategorias = idCategorias;
       this.alimentoses = alimentoses;
    }
   
     @Id 

    
    @Column(name="idCategorias", unique=true, nullable=false, length=70)
    public String getIdCategorias() {
        return this.idCategorias;
    }
    
    public void setIdCategorias(String idCategorias) {
        this.idCategorias = idCategorias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categorias")
    public Set getAlimentoses() {
        return this.alimentoses;
    }
    
    public void setAlimentoses(Set alimentoses) {
        this.alimentoses = alimentoses;
    }




}


