package edu.eci.cosw.persistenceexercises.simplepersistencelayer;
// Generated Feb 15, 2015 1:34:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Combos generated by hbm2java
 */
@Entity
@Table(name="Combos"
    ,catalog="coswg1"
)
public class Combos  implements java.io.Serializable {


     private int productoIdProductos;
     private Productos productos;
     private String nombre;
     private Set alimentoses = new HashSet(0);

    public Combos() {
    }

	
    public Combos(Productos productos) {
        this.productos = productos;
    }
    public Combos(Productos productos, String nombre, Set alimentoses) {
       this.productos = productos;
       this.nombre = nombre;
       this.alimentoses = alimentoses;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="productos"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="Producto_idProductos", unique=true, nullable=false)
    public int getProductoIdProductos() {
        return this.productoIdProductos;
    }
    
    public void setProductoIdProductos(int productoIdProductos) {
        this.productoIdProductos = productoIdProductos;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }

    
    @Column(name="Nombre", length=70)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="combos")
    public Set getAlimentoses() {
        return this.alimentoses;
    }
    
    public void setAlimentoses(Set alimentoses) {
        this.alimentoses = alimentoses;
    }




}


