package edu.eci.cosw.persistenceexercises.simplepersistencelayer;
// Generated Feb 15, 2015 1:34:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Franquicias generated by hbm2java
 */
@Entity
@Table(name="Franquicias"
    ,catalog="coswg1"
)
public class Franquicias  implements java.io.Serializable {


     private String idFranquicia;
     private Float porcentajeAcordado;
     private Set sucursaleses = new HashSet(0);

    public Franquicias() {
    }

	
    public Franquicias(String idFranquicia) {
        this.idFranquicia = idFranquicia;
    }
    public Franquicias(String idFranquicia, Float porcentajeAcordado, Set sucursaleses) {
       this.idFranquicia = idFranquicia;
       this.porcentajeAcordado = porcentajeAcordado;
       this.sucursaleses = sucursaleses;
    }
   
     @Id 

    
    @Column(name="idFranquicia", unique=true, nullable=false, length=45)
    public String getIdFranquicia() {
        return this.idFranquicia;
    }
    
    public void setIdFranquicia(String idFranquicia) {
        this.idFranquicia = idFranquicia;
    }

    
    @Column(name="porcentajeAcordado", precision=12, scale=0)
    public Float getPorcentajeAcordado() {
        return this.porcentajeAcordado;
    }
    
    public void setPorcentajeAcordado(Float porcentajeAcordado) {
        this.porcentajeAcordado = porcentajeAcordado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="franquicias")
    public Set getSucursaleses() {
        return this.sucursaleses;
    }
    
    public void setSucursaleses(Set sucursaleses) {
        this.sucursaleses = sucursaleses;
    }




}


