package edu.eci.cosw.persistenceexercises.simplepersistencelayer;
// Generated Feb 15, 2015 1:34:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name="Productos"
    ,catalog="coswg1"
)
public class Productos  implements java.io.Serializable {


     private Integer idProductos;
     private Sucursales sucursales;
     private float precio;
     private Alimentos alimentos;
     private Combos combos;
     private Set pedidoses = new HashSet(0);

    public Productos() {
    }

	
    public Productos(Sucursales sucursales, float precio) {
        this.sucursales = sucursales;
        this.precio = precio;
    }
    public Productos(Sucursales sucursales, float precio, Alimentos alimentos, Combos combos, Set pedidoses) {
       this.sucursales = sucursales;
       this.precio = precio;
       this.alimentos = alimentos;
       this.combos = combos;
       this.pedidoses = pedidoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idProductos", unique=true, nullable=false)
    public Integer getIdProductos() {
        return this.idProductos;
    }
    
    public void setIdProductos(Integer idProductos) {
        this.idProductos = idProductos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Sucursales_idSucursales", nullable=false)
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }

    
    @Column(name="Precio", nullable=false, precision=12, scale=0)
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="productos")
    public Alimentos getAlimentos() {
        return this.alimentos;
    }
    
    public void setAlimentos(Alimentos alimentos) {
        this.alimentos = alimentos;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="productos")
    public Combos getCombos() {
        return this.combos;
    }
    
    public void setCombos(Combos combos) {
        this.combos = combos;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="Pedidos_Productos", catalog="coswg1", joinColumns = { 
        @JoinColumn(name="Producto_idProductos", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Pedidos_idPedidos", nullable=false, updatable=false) })
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }




}


