package edu.eci.cosw.persistenceexercises.simplepersistencelayer;
// Generated Feb 15, 2015 1:34:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sucursales generated by hbm2java
 */
@Entity
@Table(name="Sucursales"
    ,catalog="coswg1"
)
public class Sucursales  implements java.io.Serializable {


     private Integer idSucursales;
     private Franquicias franquicias;
     private PlazoletaComidas plazoletaComidas;
     private Set productoses = new HashSet(0);

    public Sucursales() {
    }

	
    public Sucursales(Franquicias franquicias, PlazoletaComidas plazoletaComidas) {
        this.franquicias = franquicias;
        this.plazoletaComidas = plazoletaComidas;
    }
    public Sucursales(Franquicias franquicias, PlazoletaComidas plazoletaComidas, Set productoses) {
       this.franquicias = franquicias;
       this.plazoletaComidas = plazoletaComidas;
       this.productoses = productoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idSucursales", unique=true, nullable=false)
    public Integer getIdSucursales() {
        return this.idSucursales;
    }
    
    public void setIdSucursales(Integer idSucursales) {
        this.idSucursales = idSucursales;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Franquicias_idFranquicia", nullable=false)
    public Franquicias getFranquicias() {
        return this.franquicias;
    }
    
    public void setFranquicias(Franquicias franquicias) {
        this.franquicias = franquicias;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="PlazoletaComidas_idPlazoletaComidas", referencedColumnName="idPlazoletaComidas", nullable=false), 
        @JoinColumn(name="PlazoletaComidas_ciudad", referencedColumnName="ciudad", nullable=false) } )
    public PlazoletaComidas getPlazoletaComidas() {
        return this.plazoletaComidas;
    }
    
    public void setPlazoletaComidas(PlazoletaComidas plazoletaComidas) {
        this.plazoletaComidas = plazoletaComidas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sucursales")
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }




}


