package edu.eci.cosw.proyecto_eff.simplepersistencelayer;
// Generated Feb 16, 2015 2:07:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Franquicia generated by hbm2java
 */
@Entity
@Table(name="Franquicias")
public class Franquicia  implements java.io.Serializable {

    private String idFranquicia;
    private Float porcentajeAcordado;
     

    public Franquicia() {
    }

	
    public Franquicia(String idFranquicia) {
        this.idFranquicia = idFranquicia;
    }
    public Franquicia(String idFranquicia, Float porcentajeAcordado) {
       this.idFranquicia = idFranquicia;
       this.porcentajeAcordado = porcentajeAcordado;
    }
   
    @Id 
    @Column(name="idFranquicia", unique=true, nullable=false, length=45)
    public String getIdFranquicia() {
        return this.idFranquicia;
    }
    
    public void setIdFranquicia(String idFranquicia) {
        this.idFranquicia = idFranquicia;
    }

    
    @Column(name="porcentajeAcordado", precision=12, scale=0)
    public Float getPorcentajeAcordado() {
        return this.porcentajeAcordado;
    }
    
    public void setPorcentajeAcordado(Float porcentajeAcordado) {
        this.porcentajeAcordado = porcentajeAcordado;
    }

}


