package edu.eci.cosw.proyecto_eff.simplepersistencelayer;
// Generated Feb 16, 2015 2:07:09 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pago generated by hbm2java
 */
@Entity
@Table(name="Pagos")
public class Pago  implements java.io.Serializable {


     private Integer idPagos;
     private Pedido pedidos;
     private Date fechaPago;
     private float monto;
     private String metodoPago;

    public Pago() {
    }

    public Pago(Pedido pedidos, Date fechaPago, float monto, String metodoPago) {
       this.pedidos = pedidos;
       this.fechaPago = fechaPago;
       this.monto = monto;
       this.metodoPago = metodoPago;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idPagos", unique=true, nullable=false)
    public Integer getIdPagos() {
        return this.idPagos;
    }
    
    public void setIdPagos(Integer idPagos) {
        this.idPagos = idPagos;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Pedidos_idPedidos", nullable=false)
    public Pedido getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Pedido pedidos) {
        this.pedidos = pedidos;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_pago", nullable=false, length=19)
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }

    
    @Column(name="monto", nullable=false, precision=12, scale=0)
    public float getMonto() {
        return this.monto;
    }
    
    public void setMonto(float monto) {
        this.monto = monto;
    }

    
    @Column(name="metodo_pago", nullable=false, length=45)
    public String getMetodoPago() {
        return this.metodoPago;
    }
    
    public void setMetodoPago(String metodoPago) {
        this.metodoPago = metodoPago;
    }
    
    



}


