package edu.eci.cosw.proyecto_eff.model;
// Generated Feb 16, 2015 2:07:09 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductoId generated by hbm2java
 */
@Embeddable
public class ProductoId  implements java.io.Serializable {


     private String idProductos;
     private int sucursalesIdSucursales;

    public ProductoId() {
    }

    public ProductoId(String idProductos, int sucursalesIdSucursales) {
       this.idProductos = idProductos;
       this.sucursalesIdSucursales = sucursalesIdSucursales;
    }
   


    @Column(name="idProductos", nullable=false, length=45)
    public String getIdProductos() {
        return this.idProductos;
    }
    
    public void setIdProductos(String idProductos) {
        this.idProductos = idProductos;
    }


    @Column(name="Sucursales_idSucursales", nullable=false)
    public int getSucursalesIdSucursales() {
        return this.sucursalesIdSucursales;
    }
    
    public void setSucursalesIdSucursales(int sucursalesIdSucursales) {
        this.sucursalesIdSucursales = sucursalesIdSucursales;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductoId) ) return false;
		 ProductoId castOther = ( ProductoId ) other; 
         
		 return ( (this.getIdProductos()==castOther.getIdProductos()) || ( this.getIdProductos()!=null && castOther.getIdProductos()!=null && this.getIdProductos().equals(castOther.getIdProductos()) ) )
 && (this.getSucursalesIdSucursales()==castOther.getSucursalesIdSucursales());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdProductos() == null ? 0 : this.getIdProductos().hashCode() );
         result = 37 * result + this.getSucursalesIdSucursales();
         return result;
   }   


}


